ALTER TABLE users
    ALTER COLUMN created_at DROP DEFAULT,
    ALTER COLUMN updated_at DROP DEFAULT,
    ALTER COLUMN created_at TYPE BIGINT USING EXTRACT(EPOCH FROM created_at)::BIGINT,
    ALTER COLUMN updated_at TYPE BIGINT USING EXTRACT(EPOCH FROM updated_at)::BIGINT,
    ALTER COLUMN created_at SET DEFAULT EXTRACT(EPOCH FROM now())::BIGINT,
    ALTER COLUMN updated_at SET DEFAULT EXTRACT(EPOCH FROM now())::BIGINT;
